apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
  namespace: homelab
data:
  Caddyfile: |
    ha.home.lan {
      reverse_proxy homeassistant.homelab.svc.cluster.local:8123
    }

    plex.home.lan {
      reverse_proxy plex.homelab.svc.cluster.local:32400
    }
