apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
        - name: caddy
          image: caddy:2
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
          volumeMounts:
            - name: caddy-config
              mountPath: /etc/caddy/Caddyfile
              subPath: Caddyfile
            - name: caddy-data
              mountPath: /data
      volumes:
        - name: caddy-config
          configMap:
            name: caddy-config
        - name: caddy-data
          emptyDir: {}
