apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
        - name: plex
          image: plexinc/pms-docker
          env:
            - name: TZ
              value: America/New_York
            - name: PLEX_CLAIM
              valueFrom:
                secretKeyRef:
                  name: plex-credentials
                  key: PLEX_CLAIM
          ports:
            - containerPort: 32400
              name: plex-web
          volumeMounts:
            - name: config
              mountPath: /config
            - name: transcode
              mountPath: /transcode
            - name: data
              mountPath: /data
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: plex-config
        - name: transcode
          persistentVolumeClaim:
            claimName: plex-transcode
        - name: data
          persistentVolumeClaim:
            claimName: plex-data
