apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /srv/plex/database
  storageClassName: ""
  claimRef:
    name: plex-config
    namespace: homelab
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: plex-config
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-transcode
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /srv/plex/transcode
  storageClassName: ""
  claimRef:
    name: plex-transcode
    namespace: homelab
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-transcode
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
  volumeName: plex-transcode
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-data
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /media/nas
  storageClassName: ""
  claimRef:
    name: plex-data
    namespace: homelab
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-data
  namespace: homelab
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: ""
  volumeName: plex-data
