apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant-config
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/ebrown/sandbox/homeassistant/config
  storageClassName: ""
  claimRef:
    name: homeassistant-config
    namespace: homelab
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-config
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeName: homeassistant-config
